run:
  timeout: 3m
  go: "" # empty -> will be read from go.mod file instead
  tests: true
  allow-parallel-runners: false
  concurrency: 4
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  govet:
    enable-all: true
  gofumpt:
    module-path: "weezel/meetup"
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and
    # can be changed with the tab-width option.
    # Default: 120.
    line-length: 120
    # Tab width in spaces.
    # Default: 1
    tab-width: 8
  nestif:
    min-complexity: 6
  gosimple:
    checks: ["all"]
linters:
  disable-all: true
  enable:
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errcheck # default
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple # default
    - govet # default
    - ineffassign # default
    - lll
    - mirror
    - nestif
    - nolintlint
    - nosprintfhostport
    - reassign
    - revive
    - sqlclosecheck
    - staticcheck # default
    - tenv
    - tparallel
    - typecheck # default
    - unconvert
    - unused # default
    - usestdlibvars
    - whitespace
    - wrapcheck
    - zerologlint
# issues:
output:
  # Sort results by: filepath, line and column.
  sort-results: true

issues:
  # Show all the results, don't hide anything
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    # Directory has generated code
    - internal/generated
  # When enabled these are skipped:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  exclude-dirs-use-default: false
